# File: azure-pipelines.yml
# Date: 30-May-2024
#
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
- master

pr:
- master
- staging

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

jobs:
  - template: azure-template-tox-job.yml
    parameters: {tox: 'format_pep8', python: '3.13', os: 'linux'}
  - template: azure-template-tox-job.yml
    parameters: {tox: 'lint_pylint', python: '3.13', os: 'linux'}
  - template: azure-template-tox-job.yml
    parameters: {tox: 'test_coverage', python: '3.13', os: 'linux'}
  #
  - template: azure-template-tox-job.yml
    parameters: {tox: 'py39', python: '3.9', os: 'linux'}
  - template: azure-template-tox-job.yml
    parameters: {tox: 'py313', python: '3.13', os: 'linux'}
  - template: azure-template-tox-job.yml
    parameters: {tox: 'py314', python: '3.14', os: 'linux'}
  #
  - template: azure-template-tox-job.yml
    parameters: {tox: 'py313', python: '3.13', os: 'macos'}
  - template: azure-template-tox-job.yml
    parameters: {tox: 'py313', python: '3.13', os: 'windows'}
  #
  - template: azure-template-publish-job.yml
    parameters: {tox: 'py313', python: '3.13', os: 'linux'}
  #
