blank_issues_enabled: true

contact_links:
  - name: General RCSB PDB questions
    url: https://www.rcsb.org/pages/contactus
    about: |
      If you have a general question about RCSB.org services and data that isn't specifically related to the `rcsb-api` package,
      please email info@rcsb.org instead of opening an issue.